# 设备ID
device_id: 226c0c32

# 包名
package: tv.danmaku.bili

# 启动app
start_app: false

# 安装包
install: iBiliPlayer-bili.apk

# mysql DB_URL mysql+pymysql://username:pwd@host/db?charset=utf8mb4 如果是空默认使用本地sqlite3
DB_URL:
